### ISSUE TITLE
Use-case: provide a battery draining rate indication for application

### ISSUE THREAD

**Issue by taste1981** [w3c/compute-pressure#126] opened 2022-09-19 07:58 UTC
Application not well optimized/configured may have higher power consumption and drains battery quicker.

If compute-pressure API could provide indication on how fast your app is draining battery (by estimated battery life if the application keeps running), this will help application update configuration at runtime (for example, decide whether to use HW encoder or SW encoder for a video conferencing app.).

Current PressureState definition uses battery level as one of the factor for reporting pressure. However, battery draining speed should also be considered. 

If you set a quota that you expect your application to run continuously on the platform, PressureState will switch accordingly on draining rate and expected battery draining out time.

**Comment by kenchris** [comment] 2022-09-19 08:01
This is related to #119

**Comment by arskama** [comment] 2023-11-09 07:57
Would this also involve that compute-pressure API would be per process (app)?

**Comment by arskama** [comment] 2024-09-17 12:17
closed as duplicate of #119

**Closed by arskama** 2024-09-17 12:17 UTC
Labels: V2
